webtalk_init -webtalk_dir /media/michal/HDD_Linux_2/LittleNet/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.sim/sim_1/behav/xsim/xsim.dir/CustomROM_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 10 18:45:47 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "975ab4fa-75fa-4d4e-ad1e-909701f6c427" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8e8bf1c592864a67993a1d3daf94cd8d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "71" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115708_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3157574262 -regid "" -xml /media/michal/HDD_Linux_2/LittleNet/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.sim/sim_1/behav/xsim/xsim.dir/CustomROM_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/michal/HDD_Linux_2/LittleNet/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.sim/sim_1/behav/xsim/xsim.dir/CustomROM_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/michal/HDD_Linux_2/LittleNet/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.sim/sim_1/behav/xsim/xsim.dir/CustomROM_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
