# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LittleNetAcc/LittleNetAcc.srcs/sources_1/ip/DSP_A_mul_B_add_PCIN_PCOUT/DSP_A_mul_B_add_PCIN_PCOUT.xci
# IP: The module: 'DSP_A_mul_B_add_PCIN_PCOUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/michal/HDD_Linux_2/LittleNet/HW/LittleNetAcc/LittleNetAcc.gen/sources_1/ip/DSP_A_mul_B_add_PCIN_PCOUT/DSP_A_mul_B_add_PCIN_PCOUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP_A_mul_B_add_PCIN_PCOUT'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LittleNetAcc/LittleNetAcc.srcs/sources_1/ip/DSP_A_mul_B_add_PCIN_PCOUT/DSP_A_mul_B_add_PCIN_PCOUT.xci
# IP: The module: 'DSP_A_mul_B_add_PCIN_PCOUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/michal/HDD_Linux_2/LittleNet/HW/LittleNetAcc/LittleNetAcc.gen/sources_1/ip/DSP_A_mul_B_add_PCIN_PCOUT/DSP_A_mul_B_add_PCIN_PCOUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP_A_mul_B_add_PCIN_PCOUT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
