# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.srcs/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/design_1_LittleNetAccAxi_0_0.xci
# IP: The module: 'design_1_LittleNetAccAxi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_ACC/DSP_A_mul_B_ACC.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_ACC || ORIG_REF_NAME==DSP_A_mul_B_ACC} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_add_C/DSP_A_mul_B_add_C.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_C || ORIG_REF_NAME==DSP_A_mul_B_add_C} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_add_C_PCOUT/DSP_A_mul_B_add_C_PCOUT.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_C_PCOUT || ORIG_REF_NAME==DSP_A_mul_B_add_C_PCOUT} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_add_PCIN/DSP_A_mul_B_add_PCIN.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_PCIN || ORIG_REF_NAME==DSP_A_mul_B_add_PCIN} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_add_PCIN_PCOUT/DSP_A_mul_B_add_PCIN_PCOUT.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_PCIN_PCOUT || ORIG_REF_NAME==DSP_A_mul_B_add_PCIN_PCOUT} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_PCOUT/DSP_A_mul_B_PCOUT.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_PCOUT || ORIG_REF_NAME==DSP_A_mul_B_PCOUT} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_STREAMER/DSP_STREAMER.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_STREAMER || ORIG_REF_NAME==DSP_STREAMER} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.srcs/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/design_1_LittleNetAccAxi_0_0.xci
# IP: The module: 'design_1_LittleNetAccAxi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_ACC/DSP_A_mul_B_ACC.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_ACC || ORIG_REF_NAME==DSP_A_mul_B_ACC} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_add_C/DSP_A_mul_B_add_C.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_C || ORIG_REF_NAME==DSP_A_mul_B_add_C} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_add_C_PCOUT/DSP_A_mul_B_add_C_PCOUT.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_C_PCOUT || ORIG_REF_NAME==DSP_A_mul_B_add_C_PCOUT} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_add_PCIN/DSP_A_mul_B_add_PCIN.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_PCIN || ORIG_REF_NAME==DSP_A_mul_B_add_PCIN} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_add_PCIN_PCOUT/DSP_A_mul_B_add_PCIN_PCOUT.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_PCIN_PCOUT || ORIG_REF_NAME==DSP_A_mul_B_add_PCIN_PCOUT} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_A_mul_B_PCOUT/DSP_A_mul_B_PCOUT.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_PCOUT || ORIG_REF_NAME==DSP_A_mul_B_PCOUT} -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/LittleNet/HW/LN_Ultra96/LN_Ultra96.gen/sources_1/bd/design_1/ip/design_1_LittleNetAccAxi_0_0/ip/DSP_STREAMER/DSP_STREAMER.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DSP_STREAMER || ORIG_REF_NAME==DSP_STREAMER} -quiet] -quiet
