# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/DSP_A_mul_B_add_C/DSP_A_mul_B_add_C.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_C || ORIG_REF_NAME==DSP_A_mul_B_add_C} -quiet] -quiet

# IP: ip/DSP_A_add_C/DSP_A_add_C.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_add_C || ORIG_REF_NAME==DSP_A_add_C} -quiet] -quiet

# IP: ip/DSP_A_mul_B_ACC/DSP_A_mul_B_ACC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_ACC || ORIG_REF_NAME==DSP_A_mul_B_ACC} -quiet] -quiet

# IP: ip/DSP_STREAMER/DSP_STREAMER.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_STREAMER || ORIG_REF_NAME==DSP_STREAMER} -quiet] -quiet

# IP: ip/DSP_A_mul_B_add_C_PCOUT/DSP_A_mul_B_add_C_PCOUT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_C_PCOUT || ORIG_REF_NAME==DSP_A_mul_B_add_C_PCOUT} -quiet] -quiet

# IP: ip/DSP_A_mul_B_add_PCIN/DSP_A_mul_B_add_PCIN.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_PCIN || ORIG_REF_NAME==DSP_A_mul_B_add_PCIN} -quiet] -quiet

# IP: ip/DSP_A_mul_B_add_PCIN_PCOUT/DSP_A_mul_B_add_PCIN_PCOUT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_add_PCIN_PCOUT || ORIG_REF_NAME==DSP_A_mul_B_add_PCIN_PCOUT} -quiet] -quiet

# IP: ip/DSP_A_mul_B_PCOUT/DSP_A_mul_B_PCOUT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_mul_B_PCOUT || ORIG_REF_NAME==DSP_A_mul_B_PCOUT} -quiet] -quiet

# IP: ip/RAM_A32_5824e_13a_B8_15a/RAM_A32_5824e_13a_B8_15a.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_A32_5824e_13a_B8_15a || ORIG_REF_NAME==RAM_A32_5824e_13a_B8_15a} -quiet] -quiet

# IP: ip/RAM_A32_2912e_12a_B8_14a/RAM_A32_2912e_12a_B8_14a.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_A32_2912e_12a_B8_14a || ORIG_REF_NAME==RAM_A32_2912e_12a_B8_14a} -quiet] -quiet

# IP: ip/RAM_A32_10400e_14a_B8_16a/RAM_A32_10400e_14a_B8_16a.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_A32_10400e_14a_B8_16a || ORIG_REF_NAME==RAM_A32_10400e_14a_B8_16a} -quiet] -quiet

# IP: ip/RAM_A32_20000e_15a_B8_17a/RAM_A32_20000e_15a_B8_17a.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_A32_20000e_15a_B8_17a || ORIG_REF_NAME==RAM_A32_20000e_15a_B8_17a} -quiet] -quiet

# IP: ip/RAM_A32_10000e_14a_B8_16a/RAM_A32_10000e_14a_B8_16a.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_A32_10000e_14a_B8_16a || ORIG_REF_NAME==RAM_A32_10000e_14a_B8_16a} -quiet] -quiet

# IP: ip/RAM_A32_75000e_17a_B8_19a/RAM_A32_75000e_17a_B8_19a.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_A32_75000e_17a_B8_19a || ORIG_REF_NAME==RAM_A32_75000e_17a_B8_19a} -quiet] -quiet

# IP: ip/RAM_A32_15000e_14a_B8_16a/RAM_A32_15000e_14a_B8_16a.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_A32_15000e_14a_B8_16a || ORIG_REF_NAME==RAM_A32_15000e_14a_B8_16a} -quiet] -quiet
