# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/DSP_A_add_C/DSP_A_add_C.xci
# IP: The module: 'DSP_A_add_C' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/DSP_A_add_C/DSP_A_add_C_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP_A_add_C'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/DSP_A_add_C/DSP_A_add_C.xci
# IP: The module: 'DSP_A_add_C' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/DSP_A_add_C/DSP_A_add_C_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP_A_add_C'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
