# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/ROM_PW_3_1/ROM_PW_3_1.xci
# IP: The module: 'ROM_PW_3_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/ROM_PW_3_1/ROM_PW_3_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_PW_3_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/ROM_PW_3_1/ROM_PW_3_1.xci
# IP: The module: 'ROM_PW_3_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/ROM_PW_3_1/ROM_PW_3_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_PW_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
