# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/RAM_A32_2912e_12a_B8_14a/RAM_A32_2912e_12a_B8_14a.xci
# IP: The module: 'RAM_A32_2912e_12a_B8_14a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/RAM_A32_2912e_12a_B8_14a/RAM_A32_2912e_12a_B8_14a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_A32_2912e_12a_B8_14a'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/RAM_A32_2912e_12a_B8_14a/RAM_A32_2912e_12a_B8_14a.xci
# IP: The module: 'RAM_A32_2912e_12a_B8_14a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/michal/HDD_Linux_2/DAC_SDC_2021/HW/LittleNetAcc_2019_1/LittleNetAcc_2019_1.srcs/sources_1/ip/RAM_A32_2912e_12a_B8_14a/RAM_A32_2912e_12a_B8_14a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_A32_2912e_12a_B8_14a'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
